[theme]
primaryColor="#1f77b4"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false
